### ISSUE TITLE
您好，返回的图片地址无法打开

### ISSUE THREAD

**Issue by liujiaqi222** [iiiiiii1/douban-imdb-api#23]
![](https://gitee.com/zyxbj/image-warehouse/raw/master/pics/Snipaste_2021-12-11_19-34-13.jpg)

![](https://gitee.com/zyxbj/image-warehouse/raw/master/pics/Snipaste_2021-12-11_19-35-17.jpg)

**Comment by bookyo** [comment]
image.querydata.org 换成  wmdb.querydata.org  这个忘记改了，等会改一下源码！
