### ISSUE TITLE
接口请求问题

### ISSUE THREAD

**Issue by chen-ziwen** [iiiiiii1/douban-imdb-api#27]
你好 https://api.wmdb.tv/movie/api 这个接口为啥我请求一次后得等很久 才能重新请求 不然会出现跨域问题 是做了请求限制吗 大概是间隔多久可以请求一次呢

**Comment by bookyo** [comment]
30S一次间隔，请求一次算一次请求，无论是否获取到数据，每天100次，测试期间的限制。后期开放APIKEY申请，可提升权限！

**Comment by chen-ziwen** [comment]
老哥 剧情简介的内容缩水有点多 渲染出来不太美观
