### ISSUE TITLE
发现加上Limit参数会有部分电影搜索不到，请帮忙看看，谢谢！

### ISSUE THREAD

**Issue by shaozhenzhou** [iiiiiii1/douban-imdb-api#28]
以下是一些无法搜索到结果的例子：
https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=Rear%20Window&year=1954
https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=The%20Birds&year=1963
https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=Psycho&year=1960

**Comment by shaozhenzhou** [comment]
> 以下是一些无法搜索到结果的例子： https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=Rear%20Window&year=1954 https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=The%20Birds&year=1963 https://api.wmdb.tv/api/v1/movie/search?limit=1&skip=0&lang=Cn&q=Psycho&year=1960

最新发现，去掉limit参数就能搜索到，比如：
https://api.wmdb.tv/api/v1/movie/search?lang=Cn&q=Psycho&year=1960

**Comment by bookyo** [comment]
算法问题  elasticsearch 权重搜索的问题 我到时候看看
