### ISSUE TITLE
请求频繁时阻止跨域

### ISSUE THREAD

**Issue by CybeResident** [iiiiiii1/douban-imdb-api#32]
**个人需求**：当请求失败时，获取响应状态码，进行请求失败的相关处理

**请求工具**：`axios`

**问题描述**：当新请求在上一次请求后 30s 内发起时，浏览器后台会先显示“无法跨域”的错误信息，然后再显示错误响应 429，导致 `axios` 获得的 `response` 为 `undefined`。请问阻止跨域是服务器端的设置吗？如果是，请问后续更新中能换一种处理方式，返回一个带有 `status` 的 `response` 吗？

![请求频繁时接口阻止跨域](https://user-images.githubusercontent.com/95691690/172770751-54be278a-24ac-48f4-9340-1e03f25a49eb.png)

**Comment by iiiiiii1** [comment]
接口限制30s只能请求一次

**Comment by CybeResident** [comment]
明白了，谢谢解答！
