### ISSUE TITLE
响应数据格式不统一

### ISSUE THREAD

**Issue by CybeResident** [iiiiiii1/douban-imdb-api#33]
**问题描述**：根据豆瓣id请求数据时，`https://api.wmdb.tv/movie/api?id=1297574` 的响应数据中，`data` 的第一项是英文，而`https://api.wmdb.tv/movie/api?id=1428581` 的响应数据中，`data` 的第一项是中文，数据格式不统一。

**Comment by bookyo** [comment]
朋友，数组不做排序，数组你自己做一个循环，查询语言类型。

**Comment by CybeResident** [comment]
明白，我也是自己过滤的，感谢解答！
