### ISSUE TITLE
豆瓣 T250 分页异常，数据重复

### ISSUE THREAD

**Issue by ALuoBo** [iiiiiii1/douban-imdb-api#36]
> https://api.wmdb.tv/api/v1/top?type=Imdb&skip=0&limit=50&lang=Cn
type为必填，可选Douban或Imdb，skip和limit为分页使用，lang调用指定语言的数据，支持Cn或者En

文档并未详细说明如何使用，经过摸索 ，个人理解为 skip 每次跳过 limit 即   skip = skip +  limit(每页条数)  
此逻辑下前 200+ 条数据正常可用，但之后出现完全重复
如
[link1](https://api.wmdb.tv/api/v1/top?type=Douban&skip=210&limit=15&lang=Cn)
[link2](https://api.wmdb.tv/api/v1/top?type=Douban&skip=225&limit=15&lang=Cn)
查询结果完全相同

**Comment by bookyo** [comment]
skip超过200就计算成200， limit超过250就计算成250，防止恶意请求。你可以用skip=200&limit=50来查询
