### ISSUE TITLE
电影名搜索匹配算法问题

### ISSUE THREAD

**Issue by aforwardz** [iiiiiii1/douban-imdb-api#37]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/19967761/197144121-b1604cee-7c28-4765-951e-784f08ac811d.png">

想问一下这里的匹配是如何做的，ES全文搜索？还是有分词匹配？如图似乎正确电影条目排到了后面，麻烦看看

**Comment by bookyo** [comment]
中文分词，这个搜索不匹配的原因是索尼克不在分词词典之中，没有做动态分词词典库的更新。
