### ISSUE TITLE
豆瓣电影api获取到的剧情简介不完整

### ISSUE THREAD

**Issue by Ricardo-Chen-Yu** [iiiiiii1/douban-imdb-api#38]
![Snipaste_2022-10-28_22-22-38](https://user-images.githubusercontent.com/113188607/198643145-d33b161b-40dd-498f-9b06-0a63a1eb0bc1.png)
![Snipaste_2022-10-28_22-22-17](https://user-images.githubusercontent.com/113188607/198643217-55939cbe-dc99-48be-8c37-79b956027d50.png)
图一是豆瓣原网页，图二是api获取到的，试了几个都不完整。

**Comment by iiiiiii1** [comment]
数据来自于全网，豆瓣只是拿来参考，不一样很正常
