### ISSUE TITLE
最近在迁移豆瓣数据，目前导入imdb的数据库的时候需要借助楼主的api来填充imdbID

### ISSUE THREAD

**Issue by murdercdh** [iiiiiii1/douban-imdb-api#39]
目前请求数据超过限制了 提示：“Sorry, your requests today are full, please upgrade your user group!”
请问：如何获取授权的楼主接口的appid和secret 或者token之类的东西，来请求接口
@iiiiiii1 @bookyo 
pls provide some token.

**Comment by bookyo** [comment]
暂时未开放申请，抱歉。
