### ISSUE TITLE
怎么获得豆瓣电影的id号? api 没办法使用了

### ISSUE THREAD

**Issue by thinkles** [iiiiiii1/douban-imdb-api#4]

**Comment by iiiiiii1** [comment]
这个看地址栏，比如 电影 怪物猎人的地址为：https://movie.douban.com/subject/26920285/，后面的26920285就是id号。

**Comment by johan456789** [comment]
有辦法透過API搜尋電影中文或英文名得到id嗎？

**Comment by godv23** [comment]
https://blog.csdn.net/weixin_41171061/article/details/83537885

**Comment by thinkles** [comment]
赞哦, 18年的文档我竟然没有发现
